name: Build, Test, and Deploy Allure Report
permissions:
  id-token: write
  repository-projects: write
  contents: write

  
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test-and-report:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Run tests and generate Allure results
      - name: Run Tests
        run: npm test

      # Generate Allure Report
      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: allure-results
          allure_report: allure-report-${{ github.run_number }}
          clean: false

      # Deploy to GitHub Pages
      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report-${{ github.run_number }}

      - name: Output the report url
        run: |
          echo "Allure Report is available at https://matekn.github.io/allure-to-pages-poc/allure-report-${{ github.run_number }}/"
