name: Build, Test, and Deploy Allure Report
permissions:
  id-token: write
  repository-projects: write
  contents: write

  
on:
  workflow_dispatch:

  pull_request:
    branches:
      - main
  push:
    branches:
      - main


jobs:
  test-and-report:
    permissions:
      contents: write
      id-token: write
      pages: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build Allure report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          allure_results: allure-results
          #gh_pages: gh-pages
          #allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
  
      - name: list files in directory
        run: |
          ls -R -la 
  deploy:
    needs: test-and-report
    permissions:
      contents: write
      id-token: write
      pages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
      - name: list all files
        run: |
          ls -R -la
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: .
          name: github-pages
      - name: deploy to github pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages


   
