name: Build, Test, and Deploy Allure Report

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test-and-report:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Run tests and generate Allure results
      - name: Run Tests
        run: npm test

      # Generate Allure Report
      - name: Generate Allure Report
        run: |
          npm install -g allure-commandline --save-dev
          npx allure generate allure-results --clean -o allure-report

      # Deploy to GitHub Pages
       - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git remote add origin https://github.com/${{ github.repository }}.git
          git checkout --orphan gh-pages
          git add -A
          git commit -m "Deploy Allure report"
          git push --force --set-upstream origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}